server:
  port: 8082
spring:
  application:
    name: ResourceService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://ResourceDb:5432/resource_db"
    username: "postgres"
    password: "1234"
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://EurekaService:8761/eureka/
token:
  signing:
    key: 53A73E5F1C4E0A2DB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8635A75327855