server:
  port: 8082
spring:
  application:
    name: test-eureca-client2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/test"
    username: "postgres"
    password: "1234"
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
token:
  signing:
    key: 53A73E5F1C4E0A2DB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8635A75327855