spring:
  application:
    name: security-security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/ruslansyrymov"
    username: "postgres"
    password: "1234"
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    keyAccess: 53A73E5F1C4E0A2DB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8635A75327855
    keyRefresh: 53A73E5F1C4E0A2D3B5FFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzrC3A596D635A75327855
server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/