server:
  port: 8080

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    expiration: 6000000
spring:
  application:
     name: GatewayApi
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
#        - id: ????EURECACLIENT
#          uri: lb://TEST-EURECA-CLIENT
#          predicates:
#            - Path=/test1/**
#          filters:
#            - AuthenticationFilter

        - id: ResourceService
          uri: lb://ResourceService
          predicates:
            - Path=/test/**
          filters:
            - AuthenticationFilter

        - id: AuthorizeService
          uri: lb://AuthorizeService
          predicates:
            - Path=/auth/**


eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://EurekaService:8761/eureka/
url:
  authValid: http://AuthorizeService:9000/auth/valid/