server:
  port: 8080

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    expiration: 6000000
spring:
  application:
     name: Gatewey
  cloud:
    gateway:
      routes:
        - id: ????EURECACLIENT
          uri: lb://TEST-EURECA-CLIENT
          predicates:
            - Path=/test1/**
          filters:
            - AuthenticationFilter

        - id: ????EURECACLIENT2
          uri: lb://TEST-EURECA-CLIENT2
          predicates:
            - Path=/test2/**
          filters:
            - AuthenticationFilter

        - id: SECURITY-SECURITY
          uri: lb://SECURITY-SECURITY
          predicates:
            - Path=/auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
url:
  authValid: http://localhost:9000/auth/valid/